#=============================================================================
#  wifi
#=============================================================================

obj-$(CONFIG_HW_WIFI) += ipv4/

obj-$(CONFIG_HW_NETFILTER_MODULE) += hw_netfilter/

obj-$(CONFIG_HW_COMMSTAT) += commstat/

obj-$(CONFIG_HW_QTAGUID_PID) += qtaguid_pid/

obj-$(CONFIG_HW_DPIMARK_MODULE) += hw_dpi_mark/

obj-$(CONFIG_HW_NETBOOSTER_MODULE) += netbooster/

obj-$(CONFIG_HW_HIDATA_HIMOS) += himos/

obj-$(CONFIG_HUAWEI_BASTET) += bastet/

