obj-$(CONFIG_DIRECT_CHARGER) += direct_charger.o sc.o lvc.o direct_charger_power_supply.o
obj-$(CONFIG_LOADSWITCH) += loadswitch/
obj-$(CONFIG_SWITCHCAP) += switchcap/
obj-$(CONFIG_INA231_FOR_CHARGE) += ina231/
