obj-$(CONFIG_HISI_CHARGER_ARCH)		+= hisi_charger.o hisi_charging_core.o
#obj-$(CONFIG_BQ25892_CHARGER)	+= bq25892/
obj-$(CONFIG_SCHARGER_V200)	    += schargerV200/
obj-$(CONFIG_SCHARGER_V300)	    += schargerV300/
obj-$(CONFIG_SCHARGER_V600)	    += schargerV600/
obj-$(CONFIG_HI6523_CHARGER_SENSORHUB)           += schargerV300_sh/
obj-$(CONFIG_HISI_CHARGER_SYS_WDG)           += hisi_charging_watchdog.o
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver/libhwsecurec/