/*
 * Automatically generated by asn1_compiler.  Do not edit
 *
 * ASN.1 parser for x509_rsakey
 */

#include "asn1_decoder.h"

extern const struct asn1_decoder oases_x509_rsakey_decoder;

extern int oases_rsa_extract_mpi(void *, size_t, unsigned char, const void *, size_t);
