#
# Makefile for hisilicon camera dot driver
#

EXTRA_CFLAGS += -Idrivers/media/huawei/camera/
EXTRA_CFLAGS += -fno-pic

obj-$(CONFIG_HISI_CAMERA_DOT_PROJECTOR) += hwdot.o
obj-$(CONFIG_HISI_CAMERA_DOT_PROJECTOR_CYC8) += cyc8/
