obj-$(CONFIG_LCD_KIT_COMMON)    += kernel/common/src/
obj-$(CONFIG_LCD_KIT_HISI)	+= kernel/hisi/src/
obj-$(CONFIG_LCD_KIT_HISI)	+= kernel/hisi/adapt/
obj-$(CONFIG_LCD_KIT_MTK)	+= kernel/mtk/src/
obj-$(CONFIG_LCD_KIT_MTK)	+= kernel/mtk/adapt/
