obj-$(CONFIG_NOVATEK_HYBRID_TS_KIT) += NVTtouch_207_ts.o
NVTtouch_207_ts-objs += NVTtouch_207_ops.o NVTtouch_207_mp.o NVTtouch_207_fw_update.o NVTtouch_207_ext_proc.o NVTtouch_206_mp_ctrlram.o
EXTRA_CFLAGS += -Iarch/arm/mach-hisi
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
