ccflags-y  += -I$(srctree)/drivers/huawei_platform/inputhub/iom7/
obj-y += hisi_aod_device.o
EXTRA_CFLAGS += -Idrivers/huawei_platform/inputhub/default\
		-Idrivers/video/fbdev/hisi/dss \
		-Idrivers/video/hisi/dss \
		-Idrivers/staging/android
