obj-$(CONFIG_HUAWEI_KSTATE)          += hw_kstate.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_kcollect.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_procnetstat.o
obj-$(CONFIG_HUAWEI_KSTATE)          += hw_kpg.o