
randomize_layout.so: randomize_layout_plugin.c
	g++ -Wall -g -Iaarch64-linux-android-4.9/lib/gcc/aarch64-linux-android/4.9.x/plugin/include -fpic -shared -fno-rtti -o $@ randomize_layout_plugin.c

structleak.so: structleak_plugin.c
	g++ -Wall -g -Iaarch64-linux-android-4.9/lib/gcc/aarch64-linux-android/4.9.x/plugin/include -fpic -shared -fno-rtti -o $@ structleak_plugin.c
