obj-$(CONFIG_HW_NETBOOSTER_MODULE) += nb_netlink.o
obj-$(CONFIG_HW_NETBOOSTER_MODULE) += video_acceleration.o
obj-$(CONFIG_HW_NETBOOSTER_MODULE) += smart_switch.o
obj-$(CONFIG_HW_NETBOOSTER_MODULE) += ai_predict.o