obj-y +=hisi_mailbox.o
obj-y +=hisi_rproc.o
obj-$(CONFIG_HISI_RPROC_TESTFILE) +=hisi_rproc_test.o
obj-$(CONFIG_HISI_MAILBOX) +=hisi_mailbox_dev.o
subdir-ccflags-$(CONFIG_HISI_BB)    += -Idrivers/hisi/mntn/blackbox/


