subdir-ccflags-$(CONFIG_HISI_BB)        += -Idrivers/hisi/mntn/blackbox/platform_lpm3

obj-$(CONFIG_HISI_SR)    += pm.o
obj-$(CONFIG_HISI_SR_DEBUG) 				+= hisi_lpregs.o
obj-$(CONFIG_HISI_SR_SYNC)					+= suspend.o


