obj-$(CONFIG_ILITEK_TDDI_TS_KIT) += ilitek_protocol.o \
	ilitek_config.o \
	ilitek_dts.o \
	ilitek_report.o \
	ilitek_ts.o \
	ilitek_parser.o \
	ilitek_mp_test.o \
	ilitek_test.o \
	ilitek_flash.o \
	ilitek_firmware.o \
	ilitek_upgrade.o \
	ilitek_userspace.o \

