obj-$(CONFIG_HW_ZEROHUNG)	+= zrhung_lastword.o zrhung_transtation.o zrhung_config.o zrhung_ioctl.o zrhung_event.o watchpoint/
ifeq ($(CONFIG_ARCH_QCOM),)
obj-$(CONFIG_HW_CGROUP_INFO) += cgroup_info.o
endif
