ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-$(CONFIG_BALONG_ONOFF)	+= power_para.o
obj-$(CONFIG_BALONG_MODEM_ONOFF)	+= power_exchange.o
obj-$(CONFIG_BALONG_MODEM_ONOFF)	+= power_on.o 
obj-$(CONFIG_BALONG_MODEM_ONOFF)	+= power_off.o
obj-$(CONFIG_BALONG_MODEM_ONOFF)	+= bsp_modem_boot.o
