# Makefile for the irda drivers.
#

# Each configuration option enables a list of files.
#obj-$(CONFIG_CYPRESS_TS_KIT)  += cypress/
obj-$(CONFIG_SYNAPTICS_TCM_TS_KIT)  += synaptics_tcm/
obj-$(CONFIG_FOCAL_TS_KIT)  += focaltech/
obj-$(CONFIG_SYNAPTICS_TS_KIT)  += synaptics/
obj-$(CONFIG_PARADE_TS_KIT)  += parade/
obj-$(CONFIG_NOVATEK_TS_KIT)  += novatek/
obj-$(CONFIG_ILITEK_TS_KIT)  += ilitek/
obj-$(CONFIG_ILITEK_TDDI_TS_KIT)  += ilitek_tddi/
obj-$(CONFIG_HIMAX_TS_KIT)  += himax/
obj-$(CONFIG_GOODIX_TS_KIT)  += goodix/
obj-$(CONFIG_GOODIX_GT1X_TS_KIT)  += gt1x/
obj-$(CONFIG_NOVATEK_HYBRID_TS_KIT)  += novatek_hybrid/
obj-$(CONFIG_ATMEL_TS_KIT)  += atmel/
obj-$(CONFIG_WACOM_TS_KIT)  += wacom/
obj-$(CONFIG_SAMSUNG_TS_KIT)  += samsung/
obj-$(CONFIG_ST_TS_KIT)  += st/
obj-$(CONFIG_HIMAX_TS_KIT_64)  += himax_64/
obj-$(CONFIG_ELAN_TS_KIT)  += elan/
obj-$(CONFIG_MSTAR_TS_KIT)  += mstar/
#ifeq ($(CONFIG_HUAWEI_TS_TEST),y)
#EXTRA_CFLAGS += -DHUAWEI_TOUCHSCREEN_TEST
#endif
#EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
