#
# Makefile for hisilicon camera fpga driver
#
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/dot/cyc8
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/dot
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/
EXTRA_CFLAGS += -fno-pic

obj-$(CONFIG_HISI_CAMERA_DOT_PROJECTOR_CYC8) += cyc8.o

