#
# Makefile for single wire devices
#

obj-$(CONFIG_HW_SW_DEVICES) += sw_core.o
obj-$(CONFIG_HW_SW_DEVICES) += sw_hid_vendor.o
obj-$(CONFIG_HW_SW_DEVICES) += sw_hid.o
obj-$(CONFIG_HW_SW_DEVICES) += sw_debug.o
obj-$(CONFIG_HW_SW_DEVICES) += sw_utils.o

#sw-objs :=    sw_core.o sw_uart.o sw_hid.o

