#
# Logger extend configuration
#

obj-$(CONFIG_LOG_SWITCH)	+= log_switch.o
obj-$(CONFIG_LOG_EXCEPTION)	+= log_exception.o
obj-$(CONFIG_LOG_EXCEPTION)	+= imonitor_events.o
obj-$(CONFIG_HWLOG_KERNEL)	+= hwlog_kernel.o

obj-$(CONFIG_HUAWEI_GOLDENEYE) += goldeneye/

obj-$(CONFIG_HUAWEI_BOOT_LOG) += boot_log/

obj-$(CONFIG_HIVIEW_SELINUX) += hiview_selinux.o
