LINUXINCLUDE += -I$(srctree)/drivers/iommu
obj-$(CONFIG_HISI_IOMMU_LEGACY) += hisi_smmu.o
obj-$(CONFIG_HISI_IODOMAIN_API) += ion-iommu-map.o
obj-$(CONFIG_HISI_IOMMU_LPAE) += hisi_smmu_lpae.o
obj-$(CONFIG_HISI_IOMMU_TEST) += hisi_smmu_test.o
obj-$(CONFIG_HISI_IOMMU_TEST) += hisi_smmu_unittest.o
obj-$(CONFIG_HISI_SVM) += hisi-svm.o
