obj-$(CONFIG_ST_TS_KIT) += fts.o
obj-$(CONFIG_ST_TS_KIT) += fts_driver_test.o
obj-$(CONFIG_ST_TS_KIT) += fts_gui.o
obj-$(CONFIG_ST_TS_KIT) += fts_lib/
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
