#
# (C) COPYRIGHT 2012-2013 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

mali_kbase-y += \
        $(MALI_PLATFORM_DIR)/mali_kbase_config_hisilicon.o \
        $(MALI_PLATFORM_DIR)/mali_kbase_hisi_callback.o

include $(src)/$(MALI_PLATFORM_DIR)/last_buffer/Kbuild
mali_kbase-$(CONFIG_HISI_LAST_BUFFER) += $(LAST_BUFFER:.c=.o)

ccflags-$(CONFIG_HISI_LAST_BUFFER) += \
        -I$(src)/$(MALI_PLATFORM_DIR)/last_buffer

subdir-ccflags-$(CONFIG_HISI_LAST_BUFFER) += \
        -I$(src)/$(MALI_PLATFORM_DIR)/last_buffer

# Compile the hisilicon base drivers.
obj-$(CONFIG_MALI_MIDGARD) += $(MALI_PLATFORM_DIR)/base/memory_group_manager/