obj-$(CONFIG_HUAWEI_EMCOM) += emcom_netlink.o
obj-$(CONFIG_HUAWEI_EMCOM) += emcom_utils.o
obj-$(CONFIG_TCP_ARGO) += argo/
obj-$(CONFIG_HUAWEI_XENGINE) += xengine/
obj-$(CONFIG_HUAWEI_EMCOM) += smartcare/
obj-$(CONFIG_HUAWEI_NWEVAL) += nweval/
