obj-$(CONFIG_ILITEK_TS_KIT) += ilitek_aim.o \
		ilitek_sensor_test.o \
		ilitek_tool.o \
		ilitek_update.o \
		ilitek_dts.o
EXTRA_CFLAGS += -Iarch/arm/mach-hisi
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver