# Hisilicon IPP Makefile
ccflags-$(CONFIG_HISPIPP_V200) += -Idrivers/hisi/ipp/v200
ccflags-$(CONFIG_HISPIPP_V210) += -Idrivers/hisi/ipp/v210


obj-$(CONFIG_HISPIPP_V200) += v200/
obj-$(CONFIG_HISPIPP_V210) += v210/

