obj-$(CONFIG_ANC_HS_INTERFACE)		+= anc_hs_interface.o
obj-$(CONFIG_ANC_HS)		+= anc_hs/
obj-$(CONFIG_ANC_MAX14744)		+= anc_max14744/
obj-$(CONFIG_ANC_NCX8293)		+= anc_ncx8293/
obj-$(CONFIG_ANC_DEFAULT)		+= anc_hs_default/