#
# Makefile for hisilicon camera fpga driver
#
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/driver_ic/lm3644
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/driver_ic
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/
EXTRA_CFLAGS += -fno-pic

obj-y += lm3644.o
