obj-$(CONFIG_BCMGPS4752) += bcm4752/
obj-$(CONFIG_BCMGPS47531) += bcm47531/
obj-$(CONFIG_BCMGPS4774) += bcm4774/
obj-$(CONFIG_BCMGPS4775) += bcm4775/
obj-$(CONFIG_BCMGPS4774LHD) += lhd/
obj-$(CONFIG_BCMGPS) += gps_bcm_common.o