#
# Makefile for hisilicon camera fpga driver
#
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/driver_ic/mp3331
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/driver_ic
EXTRA_CFLAGS += -Idrivers/media/huawei/camera/
EXTRA_CFLAGS += -fno-pic

obj-$(CONFIG_HISI_CAMERA_DRIVER_IC_MP3331) += mp3331.o
