# Switch Class Driver
obj-$(CONFIG_SWITCH_USB_CLS)	+= switch_usb_class.o
obj-$(CONFIG_SWITCH_FSA9685)	+= switch_fsa9685.o
obj-$(CONFIG_SWITCH_FSA9685)	+= usbswitch_fsa9685.o
obj-$(CONFIG_SWITCH_FSA9685)	+= usbswitch_rt8979.o
