obj-$(CONFIG_HI3650_DDRC_FLUX) += hi3650_ddr_ddrcflux.o
obj-$(CONFIG_HI6250_DDRC_FLUX) += hi6250_ddr_ddrcflux.o
obj-$(CONFIG_HISI_DDRC_FLUX) += hisi_ddr_ddrcflux.o
obj-$(CONFIG_HISI_DDR_TRACKING) += hisi_ddr_tracking.o

obj-$(CONFIG_HISI_DDRC_SEC) += hisi_ddr_secprotect.o
obj-$(CONFIG_HI3660_DDR_AUTO_FSGT) += hi3660_ddr_autofsgt_proxy_kernel.o
obj-$(CONFIG_KIRIN970_DDR_AUTO_FSGT) += kirin970_ddr_autofsgt_proxy_kernel.o
obj-$(CONFIG_DDR_AUTO_FSGT) += ddr_autofsgt_proxy_kernel.o
subdir-ccflags-$(CONFIG_HISI_BB) += 	-Idrivers/hisi/mntn/blackbox \
					-I$(srctree)/drivers/hisi/tzdriver/libhwsecurec

