/*
 * File:  strings.c
 *
 * A selection of string constants for debug output...
 *
 * NOTE!  These need to stay aligned and up to date with the ENUM values
 *        that are used to index into them.
 */

const char *str_PortType[] = {"Snk", "Src", "DRP"};
const char *str_CurrentAdvert[] = {"Open", " Def", "1.5A", "3.0A"};
const char *str_Term[] = {" Open", "   Ra", "RdUSB", "Rd1.5", "Rd3.0", "Undef"};
const char *str_SrcTerm[] = {" Open", "   Ra", "   Rd", "Undef"};
const char *str_SnkTerm[] = {" Open", " Rdef", " R1.5", " R3.0"};

const char *str_TypeCStateNames[] = {
    "Disabled",
    "ErrorRecovery",
    "Unattached",
    "AttachWaitSink",
    "AttachedSink",
    "AttachWaitSource",
    "AttachedSource",
    "TrySource",
    "TryWaitSink",
    "TrySink",
    "TryWaitSource",
    "AudioAccessory",
    "DebugAccessory",
    "AttachWaitAccessory",
    "PoweredAccessory",
    "UnsupportedAccessory",
    "DelayUnattached",
    "UnattachedSource"
};

const char *str_PDStateNames[] = {
    "peDisabled",
    "peErrorRecovery",
    "peSourceHardReset",
    "peSourceSendHardReset",
    "peSourceSoftReset",
    "peSourceSendSoftReset",
    "peSourceStartup",
    "peSourceSendCaps",
    "peSourceDiscovery",
    "peSourceDisabled",
    "peSourceTransitionDefault",
    "peSourceNegotiateCap",
    "peSourceCapabilityResponse",
    "peSourceTransitionSupply",
    "peSourceReady",
    "peSourceGiveSourceCaps",
    "peSourceGetSinkCaps",
    "peSourceSendPing",
    "peSourceGotoMin",
    "peSourceGiveSinkCaps",
    "peSourceGetSourceCaps",
    "peSourceSendDRSwap",
    "peSourceEvaluateDRSwap",
    "peSinkHardReset",
    "peSinkSendHardReset",
    "peSinkSoftReset",
    "peSinkSendSoftReset",
    "peSinkTransitionDefault",
    "peSinkStartup",
    "peSinkDiscovery",
    "peSinkWaitCaps",
    "peSinkEvaluateCaps",
    "peSinkSelectCapability",
    "peSinkTransitionSink",
    "peSinkReady",
    "peSinkGiveSinkCap",
    "peSinkGetSourceCap",
    "peSinkGetSinkCap",
    "peSinkGiveSourceCap",
    "peSinkSendDRSwap",
    "peSinkEvaluateDRSwap",
    "peSourceSendVCONNSwap",
    "peSinkEvaluateVCONNSwap",
    "peSourceSendPRSwap",
    "peSourceEvaluatePRSwap",
    "peSinkSendPRSwap",
    "peSinkEvaluatePRSwap",
    "peGiveVdm",
    "peUfpVdmGetIdentity",
    "peUfpVdmSendIdentity",
    "peUfpVdmGetSvids",
    "peUfpVdmSendSvids",
    "peUfpVdmGetModes",
    "peUfpVdmSendModes",
    "peUfpVdmEvaluateModeEntry",
    "peUfpVdmModeEntryNak",
    "peUfpVdmModeEntryAck",
    "peUfpVdmModeExit",
    "peUfpVdmModeExitNak",
    "peUfpVdmModeExitAck",
    "peUfpVdmAttentionRequest",
    "peDfpUfpVdmIdentityRequest",
    "peDfpUfpVdmIdentityAcked",
    "peDfpUfpVdmIdentityNaked",
    "peDfpCblVdmIdentityRequest",
    "peDfpCblVdmIdentityAcked",
    "peDfpCblVdmIdentityNaked",
    "peDfpVdmSvidsRequest",
    "peDfpVdmSvidsAcked",
    "peDfpVdmSvidsNaked",
    "peDfpVdmModesRequest",
    "peDfpVdmModesAcked",
    "peDfpVdmModesNaked",
    "peDfpVdmModeEntryRequest",
    "peDfpVdmModeEntryAcked",
    "peDfpVdmModeEntryNaked",
    "peDfpVdmModeExitRequest",
    "peDfpVdmExitModeAcked",
    "peSrcVdmIdentityRequest",
    "peSrcVdmIdentityAcked",
    "peSrcVdmIdentityNaked",
    "peDfpVdmAttentionRequest",
    "peCblReady",
    "peCblGetIdentity",
    "peCblGetIdentityNak",
    "peCblSendIdentity",
    "peCblGetSvids",
    "peCblGetSvidsNak",
    "peCblSendSvids",
    "peCblGetModes",
    "peCblGetModesNak",
    "peCblSendModes",
    "peCblEvaluateModeEntry",
    "peCblModeEntryAck",
    "peCblModeEntryNak",
    "peCblModeExit",
    "peCblModeExitAck",
    "peCblModeExitNak",
    "peDpRequestStatus",
    "PE_BIST_Receive_Mode",
    "PE_BIST_Frame_Received",
    "PE_BIST_Carrier_Mode_2",
    "peSourceWaitNewCapabilities",
    "PE_BIST_Test_Data",
    "peSourceEvaluateVCONNSwap",
};
