obj-$(CONFIG_RMEMCHECK) += rSharedMemCheck.o
rSharedMemCheck-objs := ../rasbase/rasbase.o ../rasbase/rasprobe.o injection_code_for_remark_shared_memory.o recheck_func_after_delay.o shared_mem_check_basic.o
