

#ifndef __HISI_CUSTOMIZE_WIFI_HI115X_H__
#define __HISI_CUSTOMIZE_WIFI_HI115X_H__

#ifdef __cplusplus
#if __cplusplus
extern "C" {
#endif
#endif

#if (_PRE_PRODUCT_ID == _PRE_PRODUCT_ID_HI1151)

//#ifdef _PRE_PLAT_FEATURE_CUSTOMIZE
/*****************************************************************************
  1 其他头文件包含
*****************************************************************************/
#include "mac_vap.h"

/*****************************************************************************
  2 宏定义
*****************************************************************************/
#define NVRAM_PARAMS_ARRAY      "nvram_params"

#define MAC_LEN                 6
#define NV_WLAN_NUM             193
#define NV_WLAN_VALID_SIZE      12
#define MAC2STR(a)              (a)[0], "**", "**", "**", (a)[4], (a)[5]
#define MACFMT                  "%02x:%s:%s:%s:%02x:%02x"
#define MAC2STR_ALL(a)          (a)[0], (a)[1], (a)[2], (a)[3], (a)[4], (a)[5]
#define MACFMT_ALL              "%02x:%02x:%02x:%02x:%02x:%02x"
#define CUS_TAG_INI                     0x11
#define CUS_TAG_DTS                     0x12
#define CUS_TAG_NV                      0x13
#define CUS_TAG_PRIV_INI                0x14
#define CALI_TXPWR_PA_DC_REF_MIN        (1000)
#define CALI_TXPWR_PA_DC_REF_MAX        (12000)
#define CALI_TXPWR_PA_DC_FRE_MIN        (0)
#define CALI_TXPWR_PA_DC_FRE_MAX        (78)
#define CALI_BT_TXPWR_PA_DC_REF_MAX     (15000)
#define RF_LINE_TXRX_GAIN_DB_2G_MIN     (-32)
#define RF_LINE_TXRX_GAIN_DB_5G_MIN     (-12)
#define PSD_THRESHOLD_MIN               (-15)
#define PSD_THRESHOLD_MAX               (-10)
#define LNA_GAIN_DB_MIN                 (-10)
#define LNA_GAIN_DB_MAX                 (20)
#define NUM_OF_NV_MAX_TXPOWER           (45)                                /* NVRAM中存储的各协议速率最大发射功率参数的个数 From:24G_11b_1M To:5G_VHT80_MCS7 */
#define NUM_OF_NV_PARAMS                (2 * NUM_OF_NV_MAX_TXPOWER + 2)     /* NVRAM中存储的参数值的总个数:每项power值对应一项scale，加上dpd开关 */
#define MAX_TXPOWER_MIN                 (130)                               /* 最大发送功率的最小有效值:130 13.0dbm */
#define MAX_TXPOWER_MAX                 (238)                               /* 最大发送功率的最小有效值: 238 23.8dbm */
#define MAX_DBB_SCALE                   (0xEE)                              /* DBB SCALE最大有效值 */
#define NUM_OF_BAND_EDGE_LIMIT          (6)                                 /* FCC边带认证参数个数 */
#define TX_RATIO_MAX                    (2000)                              /* tx占空比的最大有效值 */
#define TX_PWR_COMP_VAL_MAX             (50)                                /* 发射功率补偿值的最大有效值 */
#define MORE_PWR_MAX                    (50)                                /* 根据温度额外补偿的发射功率的最大有效值 */
#define COUNTRY_CODE_LEN                (3)                                 /* 国家码位数 */
#define MAX_COUNTRY_COUNT               (300)                               /* 支持定制的国家的最大个数 */
#define MAX_CHIPID_COUNT                (8)                                 /* 支持最大chip个数 */
#define CHIPID_CFG_LEN                  (32)                                /* CHIP配置: 对应哪个设备和频段 */
#define DELTA_CCA_ED_HIGH_TH_RANGE      15                                  /* δ调整上限，最大向上或向下调整15dB */

#if defined (_PRE_WLAN_FEATURE_RX_AGGR_EXTEND) || defined (_PRE_FEATURE_WAVEAPP_CLASSIFY)
#define MAX_IXIA_MAC_ADDR_COUNT          (10)
#define IXIA_MAC_ADDR_CFG_LEN            (32)
#endif

#ifdef _PRE_WLAN_MAC_ADDR_EDCA_FIX
#define MAX_EDCA_MAC_ADDR_COUNT          (10)                                 /* 支持最大mac addr 个数，用来固定edca参数 */
#define MAC_ADDR_CFG_LEN                 (40)                                /*带:号的mac地址的最大长度 */
#endif

/* 计算绝对值 */
#define CUS_ABS(val)                    ((val) > 0 ? (val) : -(val))

/* 判断CCA能量门限调整值是否超出范围, 最大调整幅度:DELTA_CCA_ED_HIGH_TH_RANGE */
#define CUS_DELTA_CCA_ED_HIGH_TH_OUT_OF_RANGE(val)  (CUS_ABS(val) > DELTA_CCA_ED_HIGH_TH_RANGE ? 1 : 0)

/*****************************************************************************
  3 枚举定义
*****************************************************************************/
typedef enum
{
   REGDOMAIN_FCC        = 0,
   REGDOMAIN_ETSI       = 1,
   REGDOMAIN_JAPAN      = 2,
   REGDOMAIN_COMMON     = 3,

   REGDOMAIN_COUNT
} regdomain_enum;

/* 定制化 DTS CONFIG ID */
typedef enum
{
#ifdef _PRE_WLAN_RF_CALI_1151V2
    /* Hi1151V200 校准序列 */
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_0,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_1,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_2,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_3,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_4,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_5,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_6,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_7,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_8,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_9,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_10,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_11,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_12,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_13,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_14,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_15,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_16,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_17,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_18,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_19,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_20,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_21,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_22,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_23,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_24,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_25,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_26,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_27,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_28,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_29,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_30,
    WLAN_CFG_DTS_CALI_1151V2_CALI_SEQ_31,
#endif

    /* 校准 */
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN1,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_START = WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN1,     /* 校准 2g TXPWR_REF起始配置ID */
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN2,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN3,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN4,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN5,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN6,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN7,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN8,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN9,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN10,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN11,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN12,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_VAL_CHAN13,

    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN1,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_START = WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN1,     /* 校准 2g TXPWR_REF起始配置ID */
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN2,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN3,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN4,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN5,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN6,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN7,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN8,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN9,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN10,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN11,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN12,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_2G_B40_VAL_CHAN13,

    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND1,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_START = WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND1,    /* 校准 5g TXPWR_REF起始配置ID */
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND2,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND3,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND4,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND5,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND6,
    WLAN_CFG_DTS_CALI_TXPWR_PA_DC_REF_5G_VAL_BAND7,
    WLAN_CFG_DTS_CALI_TONE_AMP_GRADE,
    WLAN_CFG_DTS_MIMO_POW_ADJUST,

    /* 动态校准开关 */
    /* 动态校准 */
    WLAN_CFG_DTS_DYN_CALI_DSCR_ITERVL,
    /* FCC认证 */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_2G_11G_TXPWR,                                                      /* FCC CH1,CH11 band edge limit */      //21
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_TXPWR_START = WLAN_CFG_DTS_BAND_EDGE_LIMIT_2G_11G_TXPWR,           /* FCC认证:TXPWR 起始配置ID */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_2G_11N_HT20_TXPWR,                                                 /* FCC CH1,CH11 band edge limit */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_2G_11N_HT40_TXPWR,                                                 /* FCC CH3,CH9 band edge limit */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_5G_11A_HT20_VHT20_TXPWR,                                           /* FCC CH36、64、100、149、165, band edge limit */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_5G_HT40_VHT40_TXPWR,                                               /* FCC CH38,CH62 、102、151，band edge limit */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_5G_VHT80_TXPWR,                                                    /* FCC CH42、58、106、155，band edge limit */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_2G_11G_DBB_SCALING,                                                /* FCC CH1,CH11 dbb scaling */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_SCALE_START = WLAN_CFG_DTS_BAND_EDGE_LIMIT_2G_11G_DBB_SCALING,     /* FCC认证:SCALE 起始配置ID */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_2G_11N_HT20_DBB_SCALING,                                           /* FCC CH1,CH11 dbb scaling */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_2G_11N_HT40_DBB_SCALING,                                           /* FCC CH3,CH9 dbb scaling */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_5G_11A_HT20_VHT20_DBB_SCALING,                                     /* FCC CH36、64、100、149、165, dbb scaling */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_5G_HT40_VHT40_DBB_SCALING,                                         /* FCC CH38,CH62 、102、151，dbb scaling */
    WLAN_CFG_DTS_BAND_EDGE_LIMIT_5G_VHT80_DBB_SCALING,                                              /* FCC CH42、58、106、155，dbb scaling */

    /* 动态校准 */
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN1,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_START = WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN1,     /* 校准 2g TXPWR_REF起始配置ID */
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN2,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN3,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN4,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN5,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN6,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN7,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN8,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN9,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN10,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN11,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN12,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C0_CHAN13,

    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN1,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN2,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN3,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN4,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN5,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN6,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN7,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN8,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN9,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN10,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN11,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN12,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_C1_CHAN13,

    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN1,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_START = WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN1,     /* 校准 2g TXPWR_REF起始配置ID */
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN2,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN3,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN4,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN5,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN6,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN7,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN8,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN9,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN10,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN11,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN12,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C0_CHAN13,

    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN1,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN2,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN3,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN4,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN5,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN6,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN7,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN8,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN9,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN10,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN11,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN12,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_2G_B40_C1_CHAN13,

    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C0_BAND1,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C0_START = WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C0_BAND1,    /* 校准 5g TXPWR_REF起始配置ID */
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C0_BAND2,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C0_BAND3,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C0_BAND4,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C0_BAND5,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C0_BAND6,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C0_BAND7,

    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C1_BAND1,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C1_BAND2,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C1_BAND3,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C1_BAND4,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C1_BAND5,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C1_BAND6,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_5G_C1_BAND7,

    WLAN_CFG_DTS_DYNC_CALI_OFDM_SINGLE_STONE_TXPOW_SPEC, /* 动态校准目标功率 */
    WLAN_CFG_DTS_DYNC_CALI_EQUIP_TXPOW_LUT,              /* 产线校准功率配置 */

    /* 动态校准天线与线缆负载差异补偿值 */
    WLAN_CFG_DTS_DYNC_CALI_POW_OFFSET_2G_C0,
    WLAN_CFG_DTS_DYNC_CALI_POW_OFFSET_2G_C1,
    WLAN_CFG_DTS_DYNC_CALI_POW_OFFSET_5G_C0_1,
    WLAN_CFG_DTS_DYNC_CALI_POW_OFFSET_5G_C1_1,
    WLAN_CFG_DTS_DYNC_CALI_POW_OFFSET_5G_C0_2,
    WLAN_CFG_DTS_DYNC_CALI_POW_OFFSET_5G_C1_2,

    /* 动态校准pow&pdet曲线多项式参数值 */
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_2G_BAND1_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_2G_BAND1_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_2G_BAND1_TRD,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_2G_BAND2_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_2G_BAND2_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_2G_BAND2_TRD,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_2G_BAND3_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_2G_BAND3_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_2G_BAND3_TRD,

    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND1_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND1_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND1_TRD,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND2_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND2_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND2_TRD,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND3_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND3_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND3_TRD,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND4_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND4_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND4_TRD,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND5_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND5_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND5_TRD,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND6_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND6_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND6_TRD,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND7_FST,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND7_SND,
    WLAN_CFG_DTS_DYNC_CALI_POLYNOMIAL_PARA_5G_BAND7_TRD,

    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_2G_PARA1,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_2G_PARA2,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_2G_PARA3,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_2G_PARA4,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_2G_PARA5,

    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_5G_PARA1,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_5G_PARA2,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_5G_PARA3,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_5G_PARA4,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_5G_PARA5,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_5G_PARA6,
    WLAN_CFG_DTS_DYNC_CALI_OFDM_DBB_5G_PARA7,

    /* dac/lpf */
    WLAN_CFG_DTS_DAC_LPF_GAIN_2G_LEGACY_RATE_1,
    WLAN_CFG_DTS_DAC_LPF_GAIN_2G_LEGACY_RATE_2,
    WLAN_CFG_DTS_DAC_LPF_GAIN_2G_LEGACY_RATE_3,
    WLAN_CFG_DTS_DAC_LPF_GAIN_2G_LEGACY_RATE_4,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_LEGACY_RATE_1,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_LEGACY_RATE_2,
    WLAN_CFG_DTS_DAC_LPF_GAIN_2G_11AC_HT20_1,
    WLAN_CFG_DTS_DAC_LPF_GAIN_2G_11AC_HT20_2,
    WLAN_CFG_DTS_DAC_LPF_GAIN_2G_11AC_HT40_1,
    WLAN_CFG_DTS_DAC_LPF_GAIN_2G_11AC_HT40_2,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_11AC_HT20_1,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_11AC_HT20_2,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_11AC_HT40_1,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_11AC_HT40_2,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_11AC_HT40_3,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_11AC_HT80_1,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_11AC_HT80_2,
    WLAN_CFG_DTS_DAC_LPF_GAIN_5G_11AC_HT80_3,

    /* rf pll */
    WLAN_CFG_DTS_RF_PLL_PPM_2G,
    WLAN_CFG_DTS_RF_PLL_PPM_5G,

    WLAN_CFG_DTS_BUTT,
}WLAN_CFG_DTS;


/* 私有定制化 PRIV CONFIG ID */
typedef enum
{
    /* 校准开关 */
    WLAN_CFG_PRIV_CALI_MASK,
    WLAN_CFG_PRIV_CALI_AUTOCALI_MASK,

    /* TBD:hal_cfg_customize_info_stru/mac_device_capability_stru */

    /* DBDC */
    WLAN_CFG_PRIV_DBDC_RADIO_0,
    WLAN_CFG_PRIV_DBDC_RADIO_1,

    WLAN_CFG_PRIV_BUTT,
}WLAN_CFG_PRIV;

/* 定制化 INI CONFIG ID */
typedef enum
{
    /* ROAM */
    WLAN_CFG_INIT_ROAM_SWITCH = 0,
    WLAN_CFG_INIT_SCAN_ORTHOGONAL,
    WLAN_CFG_INIT_TRIGGER_B,
    WLAN_CFG_INIT_TRIGGER_A,
    WLAN_CFG_INIT_DELTA_B,
    WLAN_CFG_INIT_DELTA_A,

    /* 性能 */
    WLAN_CFG_INIT_AMPDU_TX_MAX_NUM,
    WLAN_CFG_INIT_USED_MEM_FOR_START,
    WLAN_CFG_INIT_USED_MEM_FOR_STOP,
    WLAN_CFG_INIT_RX_ACK_LIMIT,
    WLAN_CFG_INIT_SDIO_D2H_ASSEMBLE_COUNT,
    WLAN_CFG_INIT_SDIO_H2D_ASSEMBLE_COUNT,

    /* 自动调频 */
#ifdef _PRE_WLAN_FEATURE_AUTO_FREQ
    WLAN_CFG_INIT_PSS_THRESHOLD_LEVEL_0,            //15
    WLAN_CFG_INIT_CPU_FREQ_LIMIT_LEVEL_0,
    WLAN_CFG_INIT_DDR_FREQ_LIMIT_LEVEL_0,
    WLAN_CFG_INIT_PSS_THRESHOLD_LEVEL_1,
    WLAN_CFG_INIT_CPU_FREQ_LIMIT_LEVEL_1,
    WLAN_CFG_INIT_DDR_FREQ_LIMIT_LEVEL_1,
    WLAN_CFG_INIT_PSS_THRESHOLD_LEVEL_2,
    WLAN_CFG_INIT_CPU_FREQ_LIMIT_LEVEL_2,
    WLAN_CFG_INIT_DDR_FREQ_LIMIT_LEVEL_2,
    WLAN_CFG_INIT_PSS_THRESHOLD_LEVEL_3,
    WLAN_CFG_INIT_CPU_FREQ_LIMIT_LEVEL_3,
    WLAN_CFG_INIT_DDR_FREQ_LIMIT_LEVEL_3,
    WLAN_CFG_INIT_DEVICE_TYPE_LEVEL_0,
    WLAN_CFG_INIT_DEVICE_TYPE_LEVEL_1,
    WLAN_CFG_INIT_DEVICE_TYPE_LEVEL_2,
    WLAN_CFG_INIT_DEVICE_TYPE_LEVEL_3,
#endif
    /* AP开Tx amsdu */
    WLAN_CFG_INIT_AP_TX_AMSDU,
    /* AP开Rx amsdu */
    WLAN_CFG_INIT_AP_RX_AMSDU,
    /* 低功耗 */
    WLAN_CFG_INIT_POWERMGMT_SWITCH,                 //31
    /* 可维可测 */
    WLAN_CFG_INIT_LOGLEVEL,
    /* 2G RF前端 */
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND1_MULT4,    //33
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND_START = WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND1_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND1_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND2_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND2_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND3_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND3_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND_END = WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_2G_BAND3_MULT10,
    /* 5G RF前端 */
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND1_MULT4,  //44
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND_START = WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND1_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND1_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND2_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND2_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND3_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND3_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND4_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND4_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND5_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND5_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND6_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND6_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND7_MULT4,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND7_MULT10,
    WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND_END = WLAN_CFG_INIT_RF_LINE_TXRX_GAIN_DB_5G_BAND7_MULT10,
    /* FEM 03考虑2g */
    WLAN_CFG_INIT_RF_LINE_RX_GAIN_DB_2G,
    WLAN_CFG_INIT_LNA_GAIN_DB_2G,
    WLAN_CFG_INIT_RF_LINE_TX_GAIN_DB_2G,
    WLAN_CFG_INIT_EXT_SWITCH_ISEXIST_2G,
    WLAN_CFG_INIT_EXT_PA_ISEXIST_2G,
    WLAN_CFG_INIT_EXT_LNA_ISEXIST_2G,
    WLAN_CFG_INIT_LNA_ON2OFF_TIME_NS_2G,
    WLAN_CFG_INIT_LNA_OFF2ON_TIME_NS_2G,
    WLAN_CFG_INIT_RF_LINE_RX_GAIN_DB_5G,
    WLAN_CFG_INIT_LNA_GAIN_DB_5G,
    WLAN_CFG_INIT_RF_LINE_TX_GAIN_DB_5G,
    WLAN_CFG_INIT_EXT_SWITCH_ISEXIST_5G,
    WLAN_CFG_INIT_EXT_PA_ISEXIST_5G,
    WLAN_CFG_INIT_EXT_LNA_ISEXIST_5G,
    WLAN_CFG_INIT_LNA_ON2OFF_TIME_NS_5G,
    WLAN_CFG_INIT_LNA_OFF2ON_TIME_NS_5G,
    /* SCAN */
    WLAN_CFG_INIT_RANDOM_MAC_ADDR_SCAN,
    /* 11AC2G */
    WLAN_CFG_INIT_11AC2G_ENABLE,                    /* 11ac2g开关 */                    //56
    WLAN_CFG_INIT_DISABLE_CAPAB_2GHT40,             /* 2ght40禁止开关 */
    WLAN_CFG_INIT_DUAL_ANTENNA_ENABLE,              /* 双天线开关 */
    /* sta keepalive*/
    WLAN_CFG_INIT_STA_KEEPALIVE_CNT_TH,             /* sta keepalive th*/
    WLAN_CFG_INIT_FAR_DIST_POW_GAIN_SWITCH,
    WLAN_CFG_INIT_FAR_DIST_DSSS_SCALE_PROMOTE_SWITCH,    /* 超远距11b 1m 2m dbb scale提升使能开关 */
#if (_PRE_MULTI_CORE_MODE_OFFLOAD_DMAC != _PRE_MULTI_CORE_MODE)
    /* beacon country ie switch */
    WLAN_CFG_INIT_BEACON_COUNTRY_IE_SWITCH,         /* beacon的country ie输出开关 */
#endif
    WLAN_CFG_INIT_DELTA_CCA_ED_HIGH_20TH_2G,
    WLAN_CFG_INIT_DELTA_CCA_ED_HIGH_40TH_2G,
    WLAN_CFG_INIT_DELTA_CCA_ED_HIGH_20TH_5G,
    WLAN_CFG_INIT_DELTA_CCA_ED_HIGH_40TH_5G,
    WLAN_CFG_INIT_OBSS_RSSI_TH,
    WLAN_CFG_INIT_DYN_BW_ENABLE,

    WLAN_CFG_INIT_BUTT,
}WLAN_CFG_INIT;//注意顺序与关键字顺序对应

/* 定制化 NVRAM PARAMS INDEX */
typedef enum
{
    NVRAM_PARAMS_INDEX_0   = 0,
    NVRAM_PARAMS_INDEX_1   = 1,
    NVRAM_PARAMS_INDEX_2   = 2,
    NVRAM_PARAMS_INDEX_3   = 3,
    NVRAM_PARAMS_INDEX_4   = 4,
    NVRAM_PARAMS_INDEX_5   = 5,
    NVRAM_PARAMS_INDEX_6   = 6,
    NVRAM_PARAMS_INDEX_7   = 7,
    NVRAM_PARAMS_INDEX_8   = 8,
    NVRAM_PARAMS_INDEX_9   = 9,
    NVRAM_PARAMS_INDEX_10  = 10,
    NVRAM_PARAMS_INDEX_11  = 11,
    NVRAM_PARAMS_INDEX_12  = 12,
    NVRAM_PARAMS_INDEX_13  = 13,
    NVRAM_PARAMS_INDEX_14  = 14,
    NVRAM_PARAMS_INDEX_15  = 15,
    NVRAM_PARAMS_INDEX_16  = 16,
    NVRAM_PARAMS_INDEX_17  = 17,
    NVRAM_PARAMS_INDEX_18  = 18,
    NVRAM_PARAMS_INDEX_19  = 19,
    NVRAM_PARAMS_INDEX_20  = 20,
    NVRAM_PARAMS_INDEX_21  = 21,
    NVRAM_PARAMS_INDEX_22  = 22,
    NVRAM_PARAMS_INDEX_23  = 23,
    NVRAM_PARAMS_INDEX_24  = 24,
    NVRAM_PARAMS_INDEX_25  = 25,
    NVRAM_PARAMS_INDEX_26  = 26,
    NVRAM_PARAMS_INDEX_27  = 27,
    NVRAM_PARAMS_INDEX_28  = 28,
    NVRAM_PARAMS_INDEX_29  = 29,
    NVRAM_PARAMS_INDEX_30  = 30,
    NVRAM_PARAMS_INDEX_31  = 31,
    NVRAM_PARAMS_INDEX_32  = 32,
    NVRAM_PARAMS_INDEX_33  = 33,
    NVRAM_PARAMS_INDEX_34  = 34,
    NVRAM_PARAMS_INDEX_35  = 35,
    NVRAM_PARAMS_INDEX_36  = 36,
    NVRAM_PARAMS_INDEX_37  = 37,
    NVRAM_PARAMS_INDEX_38  = 38,
    NVRAM_PARAMS_INDEX_39  = 39,
    NVRAM_PARAMS_INDEX_40  = 40,
    NVRAM_PARAMS_INDEX_41  = 41,
    NVRAM_PARAMS_INDEX_42  = 42,
    NVRAM_PARAMS_INDEX_43  = 43,
    NVRAM_PARAMS_INDEX_44  = 44,
    NVRAM_PARAMS_INDEX_45  = 45,
    NVRAM_PARAMS_INDEX_46  = 46,
    NVRAM_PARAMS_INDEX_47  = 47,
    NVRAM_PARAMS_INDEX_48  = 48,
    NVRAM_PARAMS_INDEX_49  = 49,
    NVRAM_PARAMS_INDEX_50  = 50,
    NVRAM_PARAMS_INDEX_51  = 51,

    NVRAM_PARAMS_INDEX_BUTT
}NVRAM_PARAMS_INDEX;

/*****************************************************************************
  7 STRUCT定义
*****************************************************************************/
typedef unsigned char countrycode_t[COUNTRY_CODE_LEN];
typedef struct
{
   regdomain_enum       en_regdomain;
   countrycode_t        auc_country_code;
} countryinfo_stru;

/**
 *  regdomain <-> plat_tag map structure
 *
 **/
typedef struct regdomain_plat_tag_map
{
    regdomain_enum  en_regdomain;
    int             plat_tag;
} regdomain_plat_tag_map_stru;

typedef struct
{
    char*   name;
    int     case_entry;
} wlan_cfg_cmd;

typedef struct
{
    oal_int32               l_val;
    oal_bool_enum_uint8     en_value_state;
}wlan_customize_private_stru;

/* 定制化HOST全局变量结构体 */
typedef struct
{
    /* ba tx 聚合数 */
    unsigned int    ul_ampdu_tx_max_num;
    /* 漫游 */
    unsigned char   uc_roam_switch;
    unsigned char   uc_roam_scan_orthogonal;
    signed char     c_roam_trigger_b;
    signed char     c_roam_trigger_a;
    signed char     c_roam_delta_b;
    signed char     c_roam_delta_a;
    /* scan */
    unsigned char   uc_random_mac_addr_scan;
    /* capab */
    unsigned char   uc_disable_capab_2ght40;
} wlan_customize_stru;

/* 不接受cust下发的切换国家码的命令
 * 1、ini文件中国家码被配置成99
 * 2、维测需要:使用hipriv命令修改过国家码
*/
typedef struct
{
    oal_bool_enum_uint8 en_country_code_ingore_ini_flag;
    oal_bool_enum_uint8 en_country_code_ingore_hipriv_flag;
} wlan_cust_country_code_ingore_flag_stru;

#if defined (_PRE_WLAN_FEATURE_RX_AGGR_EXTEND) || defined (_PRE_FEATURE_WAVEAPP_CLASSIFY)
typedef struct
{
    oal_uint8       auc_user_mac_addr[WLAN_MAC_ADDR_LEN];
    oal_uint8       auc_resv[2];
} wlan_ixia_mac_addr_stru;
#endif

#ifdef _PRE_WLAN_MAC_ADDR_EDCA_FIX
typedef struct
{
    oal_uint8       auc_user_mac_addr[WLAN_MAC_ADDR_LEN];
    oal_uint8       uc_up_edca;
    oal_uint8       uc_down_edca;
} wlan_edca_mac_addr_stru;
#endif

extern wlan_cust_country_code_ingore_flag_stru g_st_cust_country_code_ignore_flag;
extern wlan_customize_stru g_st_wlan_customize_etc;
extern int hwifi_config_init_etc(int);
extern int hwifi_get_init_value_etc(int, int);
extern char *hwifi_get_country_code_etc(void);
extern void hwifi_set_country_code_etc(char*, const unsigned int);
extern int hwifi_get_mac_addr_etc(unsigned char *);
extern unsigned short *hwifi_get_nvram_params_etc(void);
extern int hwifi_is_regdomain_changed_etc(const countrycode_t, const countrycode_t);
extern int hwifi_get_cfg_params(void);
extern oal_int32 hwifi_get_init_priv_value(oal_int32 l_cfg_id, oal_int32 *pl_priv_value);
extern char* hwifi_get_chip_id_cfg(oal_uint8 uc_chip_id);
#ifdef _PRE_WLAN_MAC_ADDR_EDCA_FIX
extern oal_void hwifi_get_edca_fix_cfg(oal_void);
extern oal_void* hwifi_get_up_down_edca(oal_uint8 *puc_mac_addr);
#endif
#if defined (_PRE_WLAN_FEATURE_RX_AGGR_EXTEND) || defined (_PRE_FEATURE_WAVEAPP_CLASSIFY)
extern oal_void hwifi_get_wavap_mac_cfg(oal_void);
extern oal_bool_enum_uint8 hwifi_wavap_classify(oal_uint8 *puc_mac_addr);
#endif

#ifdef _PRE_WLAN_FEATURE_TPC_OVER_TEMP_PROTECT
extern oal_int32 hwifi_get_custom_over_temp(oal_uint8 *puc_temp);
#endif
extern regdomain_enum hwifi_get_regdomain_from_country_code(const countrycode_t country_code, oal_bool_enum_uint8 en_real_regdomain);
//#endif /* #ifdef _PRE_PLAT_FEATURE_CUSTOMIZE */

#endif //#if (_PRE_PRODUCT_ID == _PRE_PRODUCT_ID_HI1151)

#if (_PRE_PRODUCT_ID_HI1151==_PRE_PRODUCT_ID)
extern int  plat_main_init(void);
extern void plat_main_exit(void);
#endif

#ifdef __cplusplus
    #if __cplusplus
        }
    #endif
#endif

#endif //hisi_customize_wifi.h

