obj-$(CONFIG_SYNAPTICS_TS_KIT) += synaptics_driver.o
synaptics_driver-objs += synaptics.o synaptics_fw_update.o synaptics_fw_s3718_update.o synaptics_fw_debug.o synaptics_dsx_test_reporting.o synaptics_debug.o

EXTRA_CFLAGS += -Iarch/arm/mach-hisi
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/lcdkit1.0/core/common
