#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y				+= dump_config.o 
obj-y				+= dump_file.o 
obj-y				+= dump_exc_ctrl.o 

