#
# Makefile for kernel SPMI framework.
#
obj-$(CONFIG_HISI_SPMI)	+= hisi-spmi-core.o

obj-$(CONFIG_HISI_SPMI)	+= hisi-spmi-controller.o

obj-$(CONFIG_HISI_SPMI)	+= of_hisi_spmi.o

obj-$(CONFIG_HISI_SPMI_DEBUG_FS)	+= hisi-spmi-dbgfs.o
