obj-$(CONFIG_ATMEL_TS_KIT) += atmel_ts.o
atmel_ts-objs += atmel_main.o atmel_fw_update.o atmel_debug.o
EXTRA_CFLAGS += -Iarch/arm/mach-hisi
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
