
obj-$(CONFIG_HISI_THERMAL_TSENSOR)	+= hisi_tsens.o
obj-$(CONFIG_HISI_THERMAL_PERIPHERAL)	+= hisi_peripheral_tm.o hisi_ntc_tm_table.o
obj-$(CONFIG_HISI_IPA_THERMAL)	+= hisi_ipa_thermal.o
obj-$(CONFIG_HISI_IPA_THERMAL)	+= board_cooling.o
obj-$(CONFIG_HISI_THERMAL_SHELL) += hisi_shell_temp.o
obj-$(CONFIG_HISI_THERMAL_AMBIENT) += hisi_ambient_temp.o
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver/libhwsecurec
