#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y				+= dump_cp_agent.o 
obj-y				+= dump_cp_wdt.o 
obj-y				+= dump_lphy_tcm.o 
obj-y				+= dump_cphy_tcm.o 
