/* MD5: dd4b440eacb5dc09a6738e8f2b746247*/
#if !defined(__PRODUCT_CONFIG_TLPS_H__)
#define __PRODUCT_CONFIG_TLPS_H__

#ifndef FEATURE_IMS
#define FEATURE_IMS FEATURE_ON 
#endif 

#ifndef FEATURE_LTE_R11
#define FEATURE_LTE_R11 FEATURE_ON 
#endif 

#ifndef FEATURE_LTE_MBMS
#define FEATURE_LTE_MBMS FEATURE_OFF 
#endif 

#ifndef FEATURE_LTE_CDMA_R11
#define FEATURE_LTE_CDMA_R11 FEATURE_OFF 
#endif 

#ifndef FEATURE_PTM
#define FEATURE_PTM FEATURE_ON 
#endif 

#ifndef FEATURE_BALONG_CL
#define FEATURE_BALONG_CL FEATURE_ON 
#endif 

#ifndef FEATURE_LTE_CAT_PART_R11
#define FEATURE_LTE_CAT_PART_R11 
#endif 

#ifndef TL_PS_MAX_TRCH_NUM_8
#define TL_PS_MAX_TRCH_NUM_8 
#endif 

#ifndef FEATURE_LPP
#define FEATURE_LPP FEATURE_ON 
#endif 

#ifndef FEATURE_TDS_WCDMA_DYNAMIC_LOAD
#define FEATURE_TDS_WCDMA_DYNAMIC_LOAD FEATURE_OFF 
#endif 

#ifndef FEATURE_CSG
#define FEATURE_CSG FEATURE_ON 
#endif 

#ifndef FEATURE_DFS_SYNC
#define FEATURE_DFS_SYNC FEATURE_OFF 
#endif 

#ifndef FEATURE_VERSION_V8
#define FEATURE_VERSION_V8 FEATURE_OFF 
#endif 

#ifndef FEATURE_DCX0_TLHPA_WRITE_PHY_NV
#define FEATURE_DCX0_TLHPA_WRITE_PHY_NV FEATURE_ON 
#endif 

#ifndef FEATURE_CSS_CLOUD_MEMORY_IMPROVE
#define FEATURE_CSS_CLOUD_MEMORY_IMPROVE FEATURE_ON 
#endif 

#ifndef FEATURE_DATA_RETRY
#define FEATURE_DATA_RETRY FEATURE_ON 
#endif 

#ifndef FEATURE_LTE_R13
#define FEATURE_LTE_R13 FEATURE_OFF 
#endif 

#ifndef FEATURE_M2M
#define FEATURE_M2M FEATURE_ON 
#endif 

#ifndef FEATURE_CSS_RAT_RECOGNIZE
#define FEATURE_CSS_RAT_RECOGNIZE FEATURE_ON 
#endif 

#ifndef FEATURE_MODEM1_SUPPORT_LTE
#define FEATURE_MODEM1_SUPPORT_LTE FEATURE_OFF 
#endif 

#ifndef FEATURE_MEM_DECREASE
#define FEATURE_MEM_DECREASE FEATURE_OFF 
#endif 

#ifndef FEATURE_CSS_DSDS_START_BGS
#define FEATURE_CSS_DSDS_START_BGS FEATURE_ON 
#endif 

#ifndef FEATURE_KIRIN970_ES_VERSION
#define FEATURE_KIRIN970_ES_VERSION FEATURE_OFF 
#endif 

#endif /*__PRODUCT_CONFIG_H__*/ 
