obj-$(CONFIG_NOVATEK_TS_KIT_3_0) += novatek_ts.o
novatek_ts-objs += nt36xxx_ops.o nt36xxx_ext_proc.o nt36xxx_fw_update.o nt36xxx_mp_ctrlram.o nt36xxx_fw_update_spi.o
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
EXTRA_CFLAGS += -Idrivers/devkit/lcdkit/lcdkit3.0/kernel/common/include