obj-$(CONFIG_ARCH_HISI_MAXFREQ)	+= of_target_cpu.o
obj-$(CONFIG_HISI_ENABLE_GET_VAL) += cpufreq_get_volt.o
obj-$(CONFIG_HISI_BIG_MAXFREQ_HOTPLUG) += hifreq_hotplug.o
obj-$(CONFIG_HISI_CPUFREQ_DT)	+= hisi_cpufreq_dt.o
obj-$(CONFIG_HISI_CPUDDR_FREQ_LINK)	+= hisi_cpuddr_freq_link.o
obj-$(CONFIG_HISI_CPUFREQ_LOWTEMP)	+= hisi_cpufreq_lowtemp.o
