obj-$(CONFIG_SYNAPTICS_TS)  += synaptics/
#obj-$(CONFIG_CYPRESS_TS)  += cypress/
#obj-$(CONFIG_CYPRESS_TS)  += cyttsp5/
obj-$(CONFIG_ATMEL_TS) += atmel/
#obj-$(CONFIG_HIDEEP_TS)  += hideep/
obj-$(CONFIG_ST_TS)  += st/
obj-$(CONFIG_HW_NOVATEK_TS) +=novatek/
