obj-$(CONFIG_ATMEL_TS) += atmel_main.o
obj-$(CONFIG_ATMEL_TS) += atmel_fw_update.o
obj-$(CONFIG_ATMEL_TS) += atmel_debug.o
EXTRA_CFLAGS += -Iarch/arm/mach-hisi
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
