obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_fb_util_hs.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_debug_hs.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_parse_hs.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_panel_adaptor_hs.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_disp.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_fake_panel.o
obj-$(CONFIG_LCDKIT_DRIVER)	+= lcdkit_display_test.o
obj-$(CONFIG_LCDKIT_DRIVER) += lcdkit_bias_bl_utility.o

EXTRA_CFLAGS += -Idrivers/video/fbdev/hisi/dss \
		-Idrivers/video/hisi/dss \
		-Idrivers/staging/android \
		-Idrivers/atfdriver \
		-Idrivers/hisi/tzdriver \
		-Idrivers/devkit/lcdkit/lcdkit1.0/include \
		-Idrivers/devkit/lcdkit/lcdkit1.0 \
		-Idrivers/devkit/lcdkit/lcdkit1.0/core/common \
		-Idrivers/devkit/tpkit
