
ADDITEM(BIO_PROC_STAGE_SUBMIT, "BIO_SUBMIT", hisi_blk_latency_bio_submit_func),
ADDITEM(BIO_PROC_STAGE_ENDBIO, "BIO_END", hisi_blk_latency_bio_endio_func),
ADDITEM(BIO_PROC_STAGE_GENERIC_MAKE_REQ, "BIO_MAKE_REQ", NULL),
ADDITEM(BIO_PROC_STAGE_WBT, "BIO_WBT_DONE", NULL),

