#sensor unification for differ platform
obj-$(CONFIG_HUAWEI_HALL_INPUTHUB) += hall/
obj-$(CONFIG_FINGERPRINT) += fingerprint/
obj-$(CONFIG_HW_TOUCH_KEY) += touch_key/
obj-$(CONFIG_SENSORS_COLOR_AP) += color_sensor/
obj-$(CONFIG_STEP_MOTOR) += step_motor/
obj-$(CONFIG_POS_HALL) += pos_hall/
