obj-$(CONFIG_SAMSUNG_TS_KIT) += sec_driver.o
sec_driver-objs += sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_ts_only_vendor.o
EXTRA_CFLAGS += -Iarch/arm/mach-hisi
EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
EXTRA_CFLAGS += -Idrivers/tzdriver
