#
# Makefile for the memory technology device drivers.
#
# Core functionality.

ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y				+= dump_modem_baseinfo.o 
obj-y				+= dump_modem_core.o 
obj-y				+= dump_modem_debug.o 
obj-y				+= dump_modem_hook.o 
obj-y				+= dump_modem_save.o 
obj-y				+= dump_modem_rdr.o 
obj-y				+= dump_modem_mem.o 
