# Makefile for the irda drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_GOODIX_GT1X_TS_KIT_3_0) += gt1x/
obj-$(CONFIG_SYNAPTICS_TS_KIT_3_0)  += synaptics/
obj-$(CONFIG_GOODIX_GTX8_TS_KIT)  += gt8x/
obj-$(CONFIG_SAMSUNG_TS_KIT_3_0)  += samsung/
obj-$(CONFIG_SYNAPTICS_TCM_TS_KIT_3_0)  += synaptics_tcm/
obj-$(CONFIG_FOCAL_TS_KIT_3_0)  += focaltech/
obj-$(CONFIG_NOVATEK_TS_KIT_3_0)  += novatek/
obj-$(CONFIG_ATMEL_TS_KIT_3_0)  += atmel/
#ifeq ($(CONFIG_HUAWEI_TS_TEST_3_0),y)
#EXTRA_CFLAGS += -DHUAWEI_TOUCHSCREEN_TEST
#endif
#EXTRA_CFLAGS += -Idrivers/hisi/tzdriver
