#
# Generic Hardware Spinlock framework
#

obj-$(CONFIG_HWSPINLOCK)		+= hwspinlock_core.o
obj-$(CONFIG_HWSPINLOCK_OMAP)		+= omap_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_QCOM)		+= qcom_hwspinlock.o
obj-$(CONFIG_HWSPINLOCK_SIRF)		+= sirf_hwspinlock.o
obj-$(CONFIG_HSEM_U8500)		+= u8500_hsem.o
obj-$(CONFIG_HISI_HWSPINLOCK)		+= hisi_hwspinlock.o
obj-$(CONFIG_HISI_HWSPINLOCK_DEBUG)	+= hisi_hwspinlock_debugfs.o
