# Makefile for the Himax touchscreen drivers. //himax_dsm.o
# drivers/input/touchscreen
ccflags-y += -I$(srctree)/drivers/devkit/tpkit
obj-$(CONFIG_HIMAX_TS_KIT_64) += himax_platform.o himax_ic.o himax_fw_update.o himax_factory_test.o  himax_debug.o


