
obj-$(CONFIG_HUAWEI_DTV_MMTUNER) += tuner_drv.o
obj-$(CONFIG_HUAWEI_DTV_MMTUNER) += tuner_drv_hw.o
obj-$(CONFIG_HUAWEI_DTV_MMTUNER) += tuner_drv_hw_spi.o
obj-$(CONFIG_HUAWEI_DTV_MMTUNER) += tuner_drv_hw_i2c.o

