#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#


obj-$(CONFIG_MALI_T830) += r20p0-01rel0/

#obj-$(CONFIG_MALI_MIMIR) += bifrost-r2p0-02dev0/
#obj-$(CONFIG_MALI_MIMIR) += bifrost-r5p0-01rel0/
#obj-$(CONFIG_MALI_MIMIR) += bifrost-r6p0-cet/
#obj-$(CONFIG_MALI_MIMIR) += bifrost-r7p0-00cet0/
#obj-$(CONFIG_MALI_MIMIR) += bifrost-r8p0-00cet0/
obj-$(CONFIG_MALI_MIMIR) += bifrost-r14p0-00cet0/

#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r2p0-03rel0/
#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r4p0-01rel0/
#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r6p0-cet/
#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r7p0-00cet0/
#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r8p0-00cet0/
#obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r10p0-00cet3/
obj-$(CONFIG_MALI_HEIMDALL) += bifrost-r14p0-00cet0/

#obj-$(CONFIG_MALI_SIGURD) += bifrost-r7p0-00cet0/
#obj-$(CONFIG_MALI_SIGURD) += bifrost-r8p0-01rel0/
#obj-$(CONFIG_MALI_SIGURD) += bifrost-r10p0-00cet3/
obj-$(CONFIG_MALI_SIGURD) += bifrost-r14p0-00cet0/

#obj-$(CONFIG_MALI_NORR) += bifrost-r6p0-cet/
#obj-$(CONFIG_MALI_NORR) += bifrost-r7p0-00cet0/
#obj-$(CONFIG_MALI_NORR) += bifrost-r8p0-00cet0/
#obj-$(CONFIG_MALI_NORR) += bifrost-r9p0-00cet0/
#obj-$(CONFIG_MALI_NORR) += bifrost-r11p0-01rel0/
obj-$(CONFIG_MALI_NORR) += bifrost-r14p0-00cet0/

#obj-$(CONFIG_MALI_TRYM) += bifrost-r11p0-01rel0/
obj-$(CONFIG_MALI_TRYM) += bifrost-r14p0-00cet0/

#obj-$(CONFIG_MALI_GONDUL) += bifrost-r11p0-01rel0/
obj-$(CONFIG_MALI_GONDUL) += bifrost-r14p0-00cet0/
